from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


DEFAULT_DIRECTORY = "LLMWiki/LocalTranscripts/{year}"
DEFAULT_SCAN_DEPTH = 5
SKIP_DIRS = {
    "$recycle.bin",
    ".cache",
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "__pycache__",
    "appdata",
    "node_modules",
    "program files",
    "program files (x86)",
    "windows",
}


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "discover":
            roots = [Path(root).expanduser() for root in args.root] if args.root else default_scan_roots()
            vaults = discover_vaults(roots, max_depth=args.max_depth)
            if args.json:
                print(json.dumps([str(vault) for vault in vaults], ensure_ascii=False, indent=2))
            else:
                for vault in vaults:
                    print(vault)
            return 0

        if args.command == "write":
            summary = load_summary(args.summary_json) if args.summary_json else {}
            vault = resolve_vault(args.vault, args.scan_root, args.max_depth)
            note_path = write_note(
                transcript_path=Path(args.transcript).expanduser(),
                vault_path=vault,
                directory_template=args.directory,
                title=args.title,
                source=args.source,
                summary=summary,
            )
            print(note_path)
            return 0
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 2


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create an Obsidian knowledge note from a local transcript text file."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    discover = subparsers.add_parser("discover", help="Scan local folders for Obsidian vaults.")
    discover.add_argument("--root", action="append", default=[], help="Root folder to scan. Repeatable.")
    discover.add_argument("--max-depth", type=int, default=DEFAULT_SCAN_DEPTH)
    discover.add_argument("--json", action="store_true", help="Print JSON list.")

    write = subparsers.add_parser("write", help="Write a Markdown note into an Obsidian vault.")
    write.add_argument("transcript", help="Local transcript text file, for example 111.txt.")
    write.add_argument("--vault", help="Obsidian Vault path. If omitted, a single discovered vault is used.")
    write.add_argument("--scan-root", action="append", default=[], help="Root folder to scan when --vault is omitted.")
    write.add_argument("--max-depth", type=int, default=DEFAULT_SCAN_DEPTH)
    write.add_argument("--directory", default=DEFAULT_DIRECTORY, help="Vault-relative directory. Supports {year} and {date}.")
    write.add_argument("--title", help="Note title. Defaults to transcript filename.")
    write.add_argument("--source", default="", help="Optional source label or source file path.")
    write.add_argument("--summary-json", help="JSON file generated by Codex or another local agent.")
    return parser


def default_scan_roots(home: Path | None = None) -> list[Path]:
    home = (home or Path.home()).expanduser()
    roots = [home / "Documents", home / "Desktop", home / "OneDrive", home]
    roots.extend(path for path in home.glob("OneDrive*") if path.is_dir())
    result: list[Path] = []
    seen: set[Path] = set()
    for root in roots:
        if root.exists() and root not in seen:
            seen.add(root)
            result.append(root)
    return result


def discover_vaults(roots: list[Path], max_depth: int = DEFAULT_SCAN_DEPTH) -> list[Path]:
    found: list[Path] = []
    seen: set[Path] = set()
    for root in roots:
        root = root.expanduser()
        if not root.exists() or not root.is_dir():
            continue
        for current, dirs, _files in os.walk(root):
            current_path = Path(current)
            depth = len(current_path.relative_to(root).parts)
            lowered = {name.lower() for name in dirs}
            if ".obsidian" in lowered:
                resolved = current_path.resolve()
                if resolved not in seen:
                    seen.add(resolved)
                    found.append(resolved)
                dirs[:] = []
                continue
            if depth >= max_depth:
                dirs[:] = []
                continue
            dirs[:] = [name for name in dirs if name.lower() not in SKIP_DIRS]
    return sorted(found, key=lambda path: str(path).lower())


def resolve_vault(vault: str | None, scan_roots: list[str], max_depth: int) -> Path:
    if vault:
        path = Path(vault).expanduser()
        ensure_vault(path)
        return path.resolve()

    roots = [Path(root).expanduser() for root in scan_roots] if scan_roots else default_scan_roots()
    vaults = discover_vaults(roots, max_depth=max_depth)
    if not vaults:
        raise ValueError("No Obsidian vault found. Pass --vault with the Vault path.")
    if len(vaults) > 1:
        joined = "\n".join(f"- {vault}" for vault in vaults)
        raise ValueError(f"Multiple Obsidian vaults found. Pass --vault explicitly:\n{joined}")
    return vaults[0]


def ensure_vault(path: Path) -> None:
    if not path.exists():
        raise ValueError(f"Obsidian Vault path does not exist: {path}")
    if not path.is_dir():
        raise ValueError(f"Obsidian Vault path is not a directory: {path}")
    if not (path / ".obsidian").exists():
        raise ValueError(f"Path does not look like an Obsidian Vault because .obsidian is missing: {path}")


def load_summary(path: str) -> dict[str, Any]:
    summary_path = Path(path).expanduser()
    data = json.loads(summary_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Summary JSON must be an object.")
    return data


def write_note(
    *,
    transcript_path: Path,
    vault_path: Path,
    directory_template: str,
    title: str | None,
    source: str,
    summary: dict[str, Any],
    created_at: datetime | None = None,
) -> Path:
    ensure_vault(vault_path)
    if not transcript_path.exists():
        raise ValueError(f"Transcript file does not exist: {transcript_path}")
    if not transcript_path.is_file():
        raise ValueError(f"Transcript path is not a file: {transcript_path}")

    created_at = created_at or datetime.now().astimezone()
    transcript_text = transcript_path.read_text(encoding="utf-8-sig")
    note_title = title or transcript_path.stem
    vault_root = vault_path.resolve()
    directory = render_directory(directory_template, created_at)
    output_dir = (vault_root / directory).resolve()
    if not is_relative_to(output_dir, vault_root):
        raise ValueError(f"Output directory escapes the Obsidian Vault: {directory_template}")
    output_dir.mkdir(parents=True, exist_ok=True)

    note_path = unique_path(output_dir / f"{created_at:%Y-%m-%d}_{sanitize_filename(note_title)}.md")
    note_path.write_text(
        render_note(
            title=note_title,
            transcript_path=transcript_path,
            transcript_text=transcript_text,
            source=source,
            summary=summary,
            created_at=created_at,
        ),
        encoding="utf-8",
    )
    return note_path


def render_directory(template: str, created_at: datetime) -> Path:
    rendered = template.format(year=f"{created_at:%Y}", date=f"{created_at:%Y-%m-%d}").strip("/\\")
    if not rendered:
        return Path()
    return Path(rendered)


def is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def render_note(
    *,
    title: str,
    transcript_path: Path,
    transcript_text: str,
    source: str,
    summary: dict[str, Any],
    created_at: datetime,
) -> str:
    tags = unique_tags(["llmwiki", "local-transcript", *string_list(summary.get("tags"))])
    lines = [
        "---",
        f"title: {yaml_quote(title)}",
        "note_type: local-transcript-summary",
        f"source: {yaml_quote(source or str(transcript_path))}",
        f"transcript_file: {yaml_quote(str(transcript_path))}",
        f"created: {yaml_quote(created_at.isoformat())}",
        "tags:",
        *[f"  - {yaml_quote(tag)}" for tag in tags],
        "---",
        "",
        f"# {title}",
        "",
        "## 知识沉淀",
        "",
        f"**主题**：{text_value(summary, 'knowledge_title', title)}",
        "",
        f"**定义**：{text_value(summary, 'knowledge_definition', text_value(summary, 'summary', '待补充。'))}",
        "",
        "## 摘要",
        "",
        text_value(summary, "summary", "待补充。"),
        "",
        "## 核心观点",
        "",
        *bullet_lines(string_list(summary.get("key_points"))),
        "",
        "## 关键概念",
        "",
        *bullet_lines(string_list(summary.get("concepts"))),
        "",
        "## 适用场景",
        "",
        *bullet_lines(string_list(summary.get("use_cases"))),
        "",
        "## 操作流程",
        "",
        *ordered_lines(string_list(summary.get("workflow_steps"))),
        "",
        "## 判断准则",
        "",
        *bullet_lines(string_list(summary.get("decision_rules"))),
        "",
        "## 常见误区",
        "",
        *bullet_lines(string_list(summary.get("pitfalls"))),
        "",
        "## 实践模板",
        "",
        *bullet_lines(string_list(summary.get("practice_template"))),
        "",
        "## 可执行事项",
        "",
        *bullet_lines(string_list(summary.get("actions")), empty="暂无明确行动项。"),
        "",
        "## 复习问题",
        "",
        *bullet_lines(string_list(summary.get("review_questions"))),
        "",
        "## 可迁移方法",
        "",
        *bullet_lines(string_list(summary.get("transferable_methods"))),
        "",
        "## 相关主题",
        "",
        *bullet_lines(string_list(summary.get("related_topics"))),
        "",
        "## 完整转写",
        "",
        transcript_text.strip() or "转写文件为空。",
        "",
    ]
    return "\n".join(lines)


def text_value(summary: dict[str, Any], key: str, default: str) -> str:
    value = summary.get(key)
    if value is None:
        return default
    text = str(value).strip()
    return text or default


def string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value.strip()] if value.strip() else []
    if not isinstance(value, list):
        return [str(value)]

    result: list[str] = []
    for item in value:
        if item is None:
            continue
        if isinstance(item, dict):
            name = item.get("name") or item.get("title") or item.get("text")
            desc = item.get("description") or item.get("summary") or item.get("explanation")
            if name and desc:
                result.append(f"{name}：{desc}")
            elif name:
                result.append(str(name))
            else:
                result.append(json.dumps(item, ensure_ascii=False))
            continue
        text = str(item).strip()
        if text:
            result.append(text)
    return result


def bullet_lines(items: list[str], empty: str = "暂无。") -> list[str]:
    if not items:
        return [empty]
    return [f"- {item}" for item in items]


def ordered_lines(items: list[str], empty: str = "暂无明确流程。") -> list[str]:
    if not items:
        return [empty]
    return [f"{index}. {item}" for index, item in enumerate(items, start=1)]


def unique_tags(tags: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for tag in tags:
        cleaned = str(tag).strip().replace("#", "").replace(" ", "-").strip("-")
        if cleaned and cleaned not in seen:
            seen.add(cleaned)
            result.append(cleaned)
    return result


def sanitize_filename(value: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", value).strip(" ._")
    return cleaned[:80] or "transcript-note"


def unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    stem = path.stem
    suffix = path.suffix
    parent = path.parent
    index = 2
    while True:
        candidate = parent / f"{stem}-{index}{suffix}"
        if not candidate.exists():
            return candidate
        index += 1


def yaml_quote(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


if __name__ == "__main__":
    raise SystemExit(main())
